#                                     Boolean masking 


Boolean masking  in numpy conatin array of truth table i.e (True/False)  and that mask the given array into boolean array that is called boolean masking.

For example  if you have array with 5 number like a=([3,10,5,9,1]) and and you apply boolean masking to this like  mask= a>5
which return a output in a boolean array like boolean array ([False ,True,False,True, False]) .

In short when you are doing boolean masking whatever value is True  by the condition you have applied i.e (>,<,==,<=) etc . in that positin  index it gives True (boolean array)other wise it gives false 


In [1]:
# importing numpy library

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
# making a numpy array  

okay = np.arange(9)
okay

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# perfoming a boolean masking by applying some condition like, >,<,<=,>= etc

masking = okay > 5
masking

array([False, False, False, False, False, False,  True,  True,  True])

In [9]:
# reshaping the okay variable into 4 x 4 
reshape = okay.reshape(3,3)
reshape

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# again performing boolean masking 

again = reshape < 6
again

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

# Boolean Indexing  i.e boolean [indexing] [ ]

Boolean Indexing ([indexing]) allows us to filter out some subset from the  array or dataset 

Basically in Boolean Indexing  only we can take filter  out element  based on specific condition i.e <,> == ,<=, != etc 

In the  boolean masking  it gives only boolean values to see this boolean values in the form of  numberical values or string values we can make use of the Boolean Indexing i.e. by applying a simple [] indexing and indexing is  denoted as []  as we know already 

In [17]:
# calling the same okay and masking variable

display(okay,masking)



array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([False, False, False, False, False, False,  True,  True,  True])

In [28]:
# Now on the same array perfoming the Boolean indexing to see its values in numerical form

boolean_indexing = okay[masking] # here okay contain  all arrays and masking variable contain boolean array i.e true ,false
boolean_indexing

array([6, 7, 8])

In [29]:
# masking on the reshape varibale 
reshape[again]

array([0, 1, 2, 3, 4, 5])

In [30]:
# seeing all the data  at one place together 
display(okay ,masking,reshape,again,boolean_indexing,reshape[again])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([False, False, False, False, False, False,  True,  True,  True])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

array([6, 7, 8])

array([0, 1, 2, 3, 4, 5])

# I think the above things are some confusing so for that im going to crate a new numpy array  and  then we will perform the Boolean Indexing

In [40]:
# creating a numpy arrays  to perform boolean indexing [ ]

hey = np.arange(15)
hey

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
# now perfoming the boolean masking which gives output in true or false like truth table

goat = hey>5 
goat

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [44]:
# now perfoming the boolean indexing [ ] which shows only True values corresponding to its position index

indexing = hey[goat]
indexing


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
# creating 2D array 

two_d = np.arange(10).reshape(2,5)
two_d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [125]:
# now perfoming the boolean indexing [ ]  which fecth true values index value

boat = two_d[two_d<3]
boat

array([0, 1, 2])

# Perfoming boolean indexing using bitwise Boolean operators in numpy 

& np.bitwise_and in this if both values are true then it will give output

| np.bitwise_or in this if one values is true then it give output 

^ np.bitwise_xor

~ np.bitwise_not in this it fill revert opposite output 

In [83]:
# making a array of  2d 

lets = np.arange(20)
lets

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [139]:
# now performing  & bitise operation 

bitwise = lets[(lets>5) | (lets>10)]
bitwise

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [123]:
c =lets[(lets>5)  & (lets>10)]
c

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [151]:
lets[lets[(lets>5)  & (lets>10)]]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [156]:
lets[lets[(lets<5) | (lets>20)]]

array([0, 1, 2, 3, 4])